/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_sblo_pandora_dice_Natives */

#ifndef _Included_jp_sblo_pandora_dice_Natives
#define _Included_jp_sblo_pandora_dice_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_sblo_pandora_dice_Natives
 * Method:    countIndexWordsNative
 * Signature: ([I[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_jp_sblo_pandora_dice_Natives_countIndexWordsNative
  (JNIEnv *, jobject, jintArray, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
